app:
  name: "AlfredoBot"
  version: "0.0.1"
  environment: "development"
  log_level: 0
  # log_file: "logs/alfredo.log"
  enable_json_logs: false

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "postgres"
  sslmode: "disable"

telegram:
  timeout: 60
  use_webhook: false

s3:
  endpoint: "https://127.0.0.1:9000"
  region: "us-east-1"
  # access_key_id: "minioadmin"
  # secret_access_key: "minioadmin"
  bucket: "alfredo-bucket"
  use_ssl: true
