version: '3.8'

services:
  postgres-db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - alfredo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  alfredo-bot:
    build:
      context: .
      target: production
    image: alfredo-bot:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["./app", "serve"]

volumes:
  alfredo-db-data: