// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Conty111/AlfredoBot/internal/app/dependencies"
	"github.com/Conty111/AlfredoBot/internal/app/initializers"
	"github.com/Conty111/AlfredoBot/internal/configs"
	"github.com/Conty111/AlfredoBot/internal/repositories"
)

// Injectors from wire.go:

func BuildApplication() (*Application, error) {
	configuration := configs.GetConfig()
	db := initializers.InitializeDatabase(configuration)
	info := initializers.InitializeBuildInfo()
	telegramUserRepository := repositories.NewTelegramUserRepository(db)
	container := &dependencies.Container{
		BuildInfo:              info,
		Config:                 configuration,
		TelegramUserRepository: telegramUserRepository,
	}
	application := &Application{
		db:        db,
		Container: container,
	}
	return application, nil
}
